{
 "title": "AlephZero Metrics",
 "description": "Grafana dashboard for substrate template metrics. Instructions on use: https://substrate.dev/docs/en/tutorials/visualize-node-metrics/",
 "tags": [
  "substrate",
  "blockchain",
  "node",
  "template",
  "polkadot",
  "kusama"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Importing -> Finalized",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aleph_Imported + aleph_Ordering + aleph_Ordered + aleph_Aggregating + aleph_Finalized"
    }
   ]
  },
  {
   "title": "Importing -> Finalized",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(aleph_Imported + aleph_Ordering + aleph_Ordered + aleph_Aggregating + aleph_Finalized)"
    },
    {
     "expr": "stddev(aleph_Imported + aleph_Ordering + aleph_Ordered + aleph_Aggregating + aleph_Finalized)"
    }
   ]
  },
  {
   "title": "Importing -> Imported",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "aleph_Imported" }
   ]
  },
  {
   "title": "Importing -> Imported (avg, stddev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(aleph_Imported)" },
    { "expr": "stddev(aleph_Imported)" }
   ]
  },
  {
   "title": "Ordered -> Aggregating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "aleph_Aggregating" }
   ]
  },
  {
   "title": "Ordered -> Aggregating (avg, stddev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(aleph_Aggregating)" },
    { "expr": "stddev(aleph_Aggregating)" }
   ]
  },
  {
   "title": "Imported -> Ordering",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "aleph_Ordering" }
   ]
  },
  {
   "title": "Imported -> Ordering (avg, stddev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(aleph_Ordering)" },
    { "expr": "stddev(aleph_Ordering)" }
   ]
  },
  {
   "title": "Aggregating -> Finalized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "aleph_Finalized" }
   ]
  },
  {
   "title": "Aggregating -> Finalized (avg, stddev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(aleph_Finalized)" },
    { "expr": "stddev(aleph_Finalized)" }
   ]
  },
  {
   "title": "Ordering -> Ordered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "aleph_Ordered" }
   ]
  },
  {
   "title": "Ordering -> Ordered (avg, stddev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(aleph_Ordered)" },
    { "expr": "stddev(aleph_Ordered)" }
   ]
  },
  { "title": "Other metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "txps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions / (aleph_Imported + aleph_Ordering + aleph_Ordered + aleph_Aggregating + aleph_Finalized)"
    }
   ]
  },
  {
   "title": "Block Height (best)",
   "type": "stat",
   "description": "What your node sees as the highest block (NOT finalized)",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\"}",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "Block Height (finalized)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\"}",
     "legendFormat": "Height(finalized)"
    }
   ]
  },
  {
   "title": "Block Total Tx",
   "type": "stat",
   "description": "Total transactions in best block",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "State Cashe (bytes)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_state_cache_bytes", "legendFormat": "Size (bytes)" }
   ]
  },
  {
   "title": "LibP2P peers",
   "type": "graph",
   "description": "Number of connected peers",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "Number of network gossip peers"
    }
   ]
  },
  {
   "title": "Max block construction time",
   "type": "timeseries",
   "description": "https://www.notion.so/cardinalcryptography/2022-03-Histogram-block-metrics-in-Substrate-4b9f2cdc083f4a4585c73429ceef077c",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n    histogram_quantile(1, rate(substrate_proposer_block_constructed_bucket{app=\"aleph-node-validator\"}[5m])),\n    \"region_ip\",\n    \"$1$2\",\n    \"instance\",\n    \"([0-9]*)\\\\.([0-9]*)\\\\..*\"\n) + on (region_ip) group_left(topology_kubernetes_io_region) 0 * count by (region_ip, topology_kubernetes_io_region)\n(\n    label_replace(\n      container_memory_max_usage_bytes{},\n      \"region_ip\",\n      \"$1$2\",\n      \"instance\",\n      \"ip-([0-9]*)-([0-9]*)-.*\"\n    )\n)",
     "legendFormat": "{{topology_kubernetes_io_region}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Max block verification time",
   "type": "timeseries",
   "description": "https://www.notion.so/cardinalcryptography/2022-03-Histogram-block-metrics-in-Substrate-4b9f2cdc083f4a4585c73429ceef077c",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n    histogram_quantile(1, rate(substrate_block_verification_time_bucket{app=\"aleph-node-validator\"}[5m])),\n    \"region_ip\",\n    \"$1$2\",\n    \"instance\",\n    \"([0-9]*)\\\\.([0-9]*)\\\\..*\"\n) + on (region_ip) group_left(topology_kubernetes_io_region) 0 * count by (region_ip, topology_kubernetes_io_region)\n(\n    label_replace(\n      container_memory_max_usage_bytes{},\n      \"region_ip\",\n      \"$1$2\",\n      \"instance\",\n      \"ip-([0-9]*)-([0-9]*)-.*\"\n    )\n)",
     "legendFormat": "{{topology_kubernetes_io_region}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Max block proposal  time",
   "type": "timeseries",
   "description": "https://www.notion.so/cardinalcryptography/2022-03-Histogram-block-metrics-in-Substrate-4b9f2cdc083f4a4585c73429ceef077c",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n    histogram_quantile(1, rate(substrate_proposer_block_proposal_time_bucket{app=\"aleph-node-validator\"}[5m])),\n    \"region_ip\",\n    \"$1$2\",\n    \"instance\",\n    \"([0-9]*)\\\\.([0-9]*)\\\\..*\"\n) + on (region_ip) group_left(topology_kubernetes_io_region) 0 * count by (region_ip, topology_kubernetes_io_region)\n(\n    label_replace(\n      container_memory_max_usage_bytes{},\n      \"region_ip\",\n      \"$1$2\",\n      \"instance\",\n      \"ip-([0-9]*)-([0-9]*)-.*\"\n    )\n)",
     "legendFormat": "{{topology_kubernetes_io_region}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Max block verification and import time",
   "type": "timeseries",
   "description": "https://www.notion.so/cardinalcryptography/2022-03-Histogram-block-metrics-in-Substrate-4b9f2cdc083f4a4585c73429ceef077c",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n    histogram_quantile(1, rate(substrate_block_verification_and_import_time_bucket{app=\"aleph-node-validator\"}[5m])),\n    \"region_ip\",\n    \"$1$2\",\n    \"instance\",\n    \"([0-9]*)\\\\.([0-9]*)\\\\..*\"\n) + on (region_ip) group_left(topology_kubernetes_io_region) 0 * count by (region_ip, topology_kubernetes_io_region)\n(\n    label_replace(\n      container_memory_max_usage_bytes{},\n      \"region_ip\",\n      \"$1$2\",\n      \"instance\",\n      \"ip-([0-9]*)-([0-9]*)-.*\"\n    )\n)",
     "legendFormat": "{{topology_kubernetes_io_region}} {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}